name: Actions Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Actions Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # https://github.com/rhysd/actionlint/blob/main/.github/actionlint-matcher.json
      - name: Setup actionlint matcher
        run: echo "::add-matcher::.github/matchers/actionlint-matcher.json"

      - name: Actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color -verbose

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          cache-dependency-path: js/pnpm-lock.yaml

      - name: pnpm install
        run: pnpm install --frozen-lockfile
        working-directory: js

      - name: format:check
        run: npx prettier --check ../.github --log-level warn
        working-directory: js
