name: Actionlint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Actionlint:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    
    # https://github.com/rhysd/actionlint/blob/main/.github/actionlint-matcher.json
    - name: Setup actionlint matcher
      run: echo "::add-matcher::.github/actionlint-matcher.json"
    
    - name: Install actionlint
      run: |
        curl -sSL https://github.com/rhysd/actionlint/releases/download/v1.7.10/actionlint_1.7.10_linux_amd64.tar.gz | tar -xz
        sudo mv actionlint /usr/local/bin/
    
    - name: Run actionlint
      run: actionlint -color -verbose
